### ISSUE TITLE
Add launchpad package generation script

### ISSUE THREAD

**Issue by eafelix** [autonomoussoftware/metronome-wallet-desktop#146]
Now the generation package for launchpad distribution is manual, we could create a bash script runnable by yarn/npm scripts in the package.json

**Comment by jcvernaleo** [comment]
We could definitely wrap up what I put in the read me in either a bash script and/or an npm script target with a few caveats.

Generating the changelog is kind of a manual thing and generating the files for each distro we want to support is also a bit manual (done through the changelog).

Also, the final files have to be signed with a key belonging to a person (not some generic bloq signing key) since it must be someone who also signed the Ubuntu Code of Conduct with that key.

So I'm totally in favor of getting most of the steps in the readmme wrapped up in a script, we won't ever be able to completely automate it.
