### ISSUE TITLE
User had no eth, but pending tx was accepted

### ISSUE THREAD

**Issue by filcap** [autonomoussoftware/metronome-wallet-desktop#38]
- User created wallet
- Started with 0 MTN 0 ETH
- User tried to buy MTN with 999 ETH
- Transaction was accepted
<img width="1164" alt="screen shot 2018-02-16 at 10 45 57 am" src="https://user-images.githubusercontent.com/24193763/36324586-c4deaace-1309-11e8-9f96-e7f6d40ec514.png">
- Transaction shows up as pending and MTN balance updated
- User tries to buy MTN again with 0 eth, but now says Insufficient funds

Here is what he sees in explorer
<img width="1053" alt="screen shot 2018-02-16 at 10 50 36 am" src="https://user-images.githubusercontent.com/24193763/36324622-f0ea843a-1309-11e8-96e3-f98a5303a5f6.png">

**Comment by filcap** [comment]
Some more info on this one
- User installed wallet (left open)
- Requested eth
- I sent him eth
- User didnt close and reopen wallet
- Atttempted to buy with 0 eth

We are thinking the issue is balance not updating until you close and reopen the wallet

**Comment by pablen** [comment]
This seems to be related to #34, the balance might have not been 0 when the purchase was executed. Cannot reproduce now that the bug is fixed, attempting to buy MTN in an auction with insufficient funds will fail. 

<img width="454" alt="captura de pantalla 2018-02-19 a la s 13 45 25" src="https://user-images.githubusercontent.com/3164763/36388821-deabe4ac-157b-11e8-9330-604465546a2e.png">
